# Site
repository: SifatMoon/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sifat A Moon
title: Computational Research Engineer 
email: sifatmoon@virgnia.edu
website: https://www.linkedin.com/in/sifatafrojmoon/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/29898135-2.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sifat Moon and I am an applied computational scientist and an ex-software engineer with a decade of experience in research and development. My background ranges from machine learning, graph theory, network science, data mining, and predictive modeling. I have pioneered several novel computational tools to model and analyze graph-based spreading processes. In my Ph.D. and postdoc, I became an expert in developing end-to-end solutions leveraging real-world data.

  I am most skilled in: <mark>Machine Learning</mark>, <mark>NetworkScience</mark>, <mark>Scalable Data Mining</mark>, <mark>High Performance Computing</mark>

content:
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Network Systems Science and Advanced Computing division, Biocomplexity Institute, University of Virginia                                                                                                
        link: Charlottesville, VA, USA      
        # link_text: boringcompany.com
        sub_title: Postdoctoral Researcher 
        caption: July 2021 - Present
        description: |
          - Lead a project with an interdisciplinary team of three members to deliver bi-weekly update on a detailed knowledge graph project to find the economic impact of under-vaccinated spatiotemporal clusters.
          
             --	3TB high-dimensional APCD (All-Payer Claims database) healthcare data, ICD-10 code, data mining, foundation model, graph neural network, recurrent neural network.
          - Develop an abductive agent-based surveillance tool to understand the political opinion on a social contact network with millions of nodes in a distributed environment. 
          
             --	HPC (High-Performance Computing) system, pattern recognition, support vector machines, XGboost.
          -	Build a graph neural network-based machine learning surrogate model for the agent-based simulation.
          
             --	Guide two junior scientists and more than four grad students.
      - layout: left
        title: Network Systems Science and Advanced Computing division, Biocomplexity Institute, University of Virginia                                                                                                
        link: Charlottesville, VA, USA      
        # link_text: boringcompany.com
        sub_title: Postdoctoral Researcher 
        caption: July 2021 - Present
        description: |
          - Lead a project with an interdisciplinary team of three members to deliver bi-weekly update on a detailed knowledge graph project to find the economic impact of under-vaccinated spatiotemporal clusters.
          
             --	3TB high-dimensional APCD (All-Payer Claims database) healthcare data, ICD-10 code, data mining, foundation model, graph neural network, recurrent neural network.
          - Develop an abductive agent-based surveillance tool to understand the political opinion on a social contact network with millions of nodes in a distributed environment. 
          
             --	HPC (High-Performance Computing) system, pattern recognition, support vector machines, XGboost.
          -	Build a graph neural network-based machine learning surrogate model for the agent-based simulation.
          
             --	Guide two junior scientists and more than four grad students.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
