# Site
repository: SifatMoon/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sifat A Moon
title: Computational Research Engineer 
email: sifatmoon@virgnia.edu
website: https://www.linkedin.com/in/sifatafrojmoon/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  SifatMoon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: sifatafrojmoon
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/29898135-2.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sifat Moon and I am an applied computational scientist and an ex-software engineer with a decade of experience in research and development. My background ranges from machine learning, graph theory, network science, data mining, and predictive modeling. I have pioneered several novel computational tools to model and analyze graph-based spreading processes. In my Ph.D. and postdoc, I became an expert in developing end-to-end solutions leveraging real-world data.

  I am most skilled in: <mark>Machine Learning</mark>, <mark>NetworkScience</mark>, <mark>Scalable Data Mining</mark>, <mark>High Performance Computing</mark>

content:
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Network Systems Science and Advanced Computing division, Biocomplexity Institute, University of Virginia                                                                                                
        link: Charlottesville, VA, USA      
        # link_text: boringcompany.com
        sub_title: Postdoctoral Researcher 
        caption: July 2021 - Present
        description: |
          - Lead a project with an interdisciplinary team of three members to deliver bi-weekly update on a detailed knowledge graph project to find the economic impact of under-vaccinated spatiotemporal clusters.
          
             --	3TB high-dimensional APCD (All-Payer Claims database) healthcare data, ICD-10 code, data mining, foundation model, graph neural network, recurrent neural network.
          - Develop an abductive agent-based surveillance tool to understand the political opinion on a social contact network with millions of nodes in a distributed environment. 
          
             --	HPC (High-Performance Computing) system, pattern recognition, support vector machines, XGboost.
          -	Build a graph neural network-based machine learning surrogate model for the agent-based simulation.
          
               --	Guide two junior scientists and more than four grad students.
      - layout: left
        title: Network Science and Engineering group, Kansas State University                                                                                               
        link: Manhattan, KS, USA      
        # link_text: boringcompany.com
        sub_title: Graduate Research Assistant
        caption: Aug 2016 – May 2021
        description: |
          - Designed a computationally efficient stochastic Monte Carlo simulation tool to understand the time-series local dynamics of the Markov spreading processes over large networks. 
          - Modified and implemented approximate Bayesian computation based on sequential Monte Carlo (ABC SMC) sampling method for a stochastic individual-level multi-layer network system. 
          -	Directed a project to estimate a movement network from NASS data using a maximum entropy reinforcement learning method to support data privacy. 

      - layout: left
        title: Samsung R&D Institute, Samsung Electronics, Samsung                                                                                              
        link: Dhaka, BD     
        # link_text: boringcompany.com
        sub_title: Software Engineer 
        caption: Aug 2013 – Aug 2016
        description: |
          - Optimized watercolor brush algorithm and pattern fill tools for the s-pen drawing bitmap engine of Galaxy Note5.
          - Developed and deployed Allshare play/Samsung Link software for Windows Phone 8.1 and an initial version of quick-connect (a convergence app of Samsung).
          -	Led a group of one software engineer and two interns for four months.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: text
        title: Kansas State University
        caption: 2016 - 2021
        sub_title: Ph.D. in Computer Engineering
        description: | # this will include new lines to allow paragraphs
          <b>CGPA:</b> 3.82/4.00

          <b>Dissertation:</b> Modeling and analysis of spreading processes over large networks from limited data.                                     

          <b>Relevant Courese:</b> Scalability for data science, multivariate statistical methods, network theory, machine learning and pattern recognition, analysis of algorithms, agent-based game theory, applied probability theory, and random process.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Reading
      - Hiking

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: SifatMoon/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
